
import './index.css'

const TopSection=()=>{
    const movie=[{id:1,"Title":"Guardians of the Galaxy","Year":"2014","imdbID":"tt2015381","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNDIzMTk4NDYtMjg5OS00ZGI0LWJhZDYtMzdmZGY1YWU5ZGNkXkEyXkFqcGdeQXVyMTI5NzUyMTIz._V1_SX300.jpg"},{id:2,"Title":"Guardians of the Galaxy Vol. 2","Year":"2017","imdbID":"tt3896198","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg"},{id:3,"Title":"Guardians of the Galaxy Vol. 3","Year":"2023","imdbID":"tt6791350","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMDgxOTdjMzYtZGQxMS00ZTAzLWI4Y2UtMTQzN2VlYjYyZWRiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg"},{id:4,"Title":"The Hitchhiker's Guide to the Galaxy","Year":"2005","imdbID":"tt0371724","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZmU5MGU4MjctNjA2OC00N2FhLWFhNWQtMzQyMGI2ZmQ0Y2YyL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{id:5,"Title":"Galaxy Quest","Year":"1999","imdbID":"tt0177789","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNmZlNTY5YjQtZTU5ZC00MzcyLWI1NDMtNjA0ZjQxMmQwYjJmL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{id:6,"Title":"The Guardians of the Galaxy Holiday Special","Year":"2022","imdbID":"tt13623136","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOGJjMzlmNzctMWI4Yi00MjcyLWFmYzAtN2JmZjU0YTM4YmRmXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_SX300.jpg"},{id:7,"Title":"The Hitchhiker's Guide to the Galaxy","Year":"1981","imdbID":"tt0081874","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BMTI2OTMwNDU1NF5BMl5BanBnXkFtZTcwOTIyNzAzMQ@@._V1_SX300.jpg"},{id:8,"Title":"Galaxy of Terror","Year":"1981","imdbID":"tt0082431","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNTE0MjkzMWItYTI3ZS00ZGRiLTllOTktMGMyNzlkMjRmZWZmXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{id:9,"Title":"The Tatami Galaxy","Year":"2010","imdbID":"tt1847445","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BODVjY2ViOWYtNjI0ZS00OGI4LTk3ZGMtOGJmMTczM2U5MTY5XkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg"},{id:10,"Title":"Super Mario Galaxy","Year":"2007","imdbID":"tt0879874","Type":"game","Poster":"https://m.media-amazon.com/images/M/MV5BOTc2ZTRkMzgtNjlmNi00NDVlLTg4NjAtZjY2NWU4ODJhNDYzXkEyXkFqcGdeQXVyNTM0MjE5NTc@._V1_SX300.jpg"}];
//    const [movies,changeMovies]= useState([{id:1,"Title":"Guardians of the Galaxy","Year":"2014","imdbID":"tt2015381","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNDIzMTk4NDYtMjg5OS00ZGI0LWJhZDYtMzdmZGY1YWU5ZGNkXkEyXkFqcGdeQXVyMTI5NzUyMTIz._V1_SX300.jpg"},{id:2,"Title":"Guardians of the Galaxy Vol. 2","Year":"2017","imdbID":"tt3896198","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg"},{id:3,"Title":"Guardians of the Galaxy Vol. 3","Year":"2023","imdbID":"tt6791350","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMDgxOTdjMzYtZGQxMS00ZTAzLWI4Y2UtMTQzN2VlYjYyZWRiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg"},{id:4,"Title":"The Hitchhiker's Guide to the Galaxy","Year":"2005","imdbID":"tt0371724","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BZmU5MGU4MjctNjA2OC00N2FhLWFhNWQtMzQyMGI2ZmQ0Y2YyL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{id:5,"Title":"Galaxy Quest","Year":"1999","imdbID":"tt0177789","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNmZlNTY5YjQtZTU5ZC00MzcyLWI1NDMtNjA0ZjQxMmQwYjJmL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{id:6,"Title":"The Guardians of the Galaxy Holiday Special","Year":"2022","imdbID":"tt13623136","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BOGJjMzlmNzctMWI4Yi00MjcyLWFmYzAtN2JmZjU0YTM4YmRmXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_SX300.jpg"},{id:7,"Title":"The Hitchhiker's Guide to the Galaxy","Year":"1981","imdbID":"tt0081874","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BMTI2OTMwNDU1NF5BMl5BanBnXkFtZTcwOTIyNzAzMQ@@._V1_SX300.jpg"},{id:8,"Title":"Galaxy of Terror","Year":"1981","imdbID":"tt0082431","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BNTE0MjkzMWItYTI3ZS00ZGRiLTllOTktMGMyNzlkMjRmZWZmXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{id:9,"Title":"The Tatami Galaxy","Year":"2010","imdbID":"tt1847445","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BODVjY2ViOWYtNjI0ZS00OGI4LTk3ZGMtOGJmMTczM2U5MTY5XkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg"},{id:10,"Title":"Super Mario Galaxy","Year":"2007","imdbID":"tt0879874","Type":"game","Poster":"https://m.media-amazon.com/images/M/MV5BOTc2ZTRkMzgtNjlmNi00NDVlLTg4NjAtZjY2NWU4ODJhNDYzXkEyXkFqcGdeQXVyNTM0MjE5NTc@._V1_SX300.jpg"}])
    return(
        <div className="back">
            <div className="movie-app">
                {movie.map(eachItem=><img src={eachItem.Poster} alt={eachItem.Title} className="images" key={eachItem.id}/> )}
            </div>
        </div>
    )
}

export default TopSection